import { pool } from "../db.js";
import bcrypt from "bcryptjs";
import { generateUsername, generatePassword } from "../utils/credentials.js";

// ─── Users ───────────────────────────────────────────────────────────────────

export async function getUsers(req, res) {
  try {
    const result = await pool.query(
      `SELECT id, username, email, first_name, last_name, role, is_active, created_at
       FROM users WHERE is_deleted = false ORDER BY created_at DESC`
    );
    res.json(result.rows);
  } catch (err) {
    console.error("getUsers error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function createUser(req, res) {
  let { username, email, first_name, last_name, password, role } = req.body;
  const normalizedFirstName = first_name?.trim();
  const normalizedLastName = last_name?.trim();
  
  // Validate required fields
  if (!normalizedFirstName || !normalizedLastName) {
    return res.status(400).json({ error: "First name and last name are required" });
  }

  // Auto-generate username and password if not provided
  const autogenerated = {};
  if (!username) {
    username = generateUsername(normalizedFirstName, normalizedLastName);
    autogenerated.username = true;
  }
  if (!password) {
    password = generatePassword();
    autogenerated.password = true;
  }

  try {
    const normalizedEmail = email?.trim() ? email.trim().toLowerCase() : null;
    const hash = await bcrypt.hash(password, 12);

    for (let attempt = 0; attempt < 8; attempt++) {
      try {
        const result = await pool.query(
          `INSERT INTO users (username, email, first_name, last_name, password_hash, role)
           VALUES ($1, $2, $3, $4, $5, $6)
           RETURNING id, username, email, first_name, last_name, role`,
          [username.trim(), normalizedEmail, normalizedFirstName, normalizedLastName, hash, role || "student"]
        );

        // Return both created user and plain text credentials if autogenerated
        const response = { user: result.rows[0] };
        if (autogenerated.username || autogenerated.password) {
          response.credentials = { username, password };
          response.autogenerated = autogenerated;
        }

        return res.status(201).json(response);
      } catch (err) {
        const isUniqueViolation = err.code === "23505";
        const isUsernameConflict =
          err.constraint === "users_username_key" || err.detail?.includes("(username)");

        if (isUniqueViolation && autogenerated.username && isUsernameConflict && attempt < 7) {
          username = generateUsername(normalizedFirstName, normalizedLastName);
          continue;
        }

        if (isUniqueViolation) {
          return res.status(409).json({ error: "Username or email already exists" });
        }

        throw err;
      }
    }
  } catch (err) {
    console.error("createUser error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function deleteUser(req, res) {
  const { userId } = req.params;
  try {
    await pool.query(`UPDATE users SET is_deleted = true WHERE id = $1`, [userId]);
    res.json({ success: true });
  } catch (err) {
    console.error("deleteUser error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

// ─── Exams ───────────────────────────────────────────────────────────────────

export async function getExams(req, res) {
  try {
    const result = await pool.query(
      `SELECT e.id, e.title, e.description, e.access_code, e.status, e.duration_minutes,
              e.total_questions, e.created_at,
              (SELECT COUNT(*) FROM exam_submissions es WHERE es.exam_id = e.id AND es.status = 'submitted') AS submission_count
       FROM exams e
       WHERE e.is_deleted = false
       ORDER BY e.created_at DESC`
    );
    res.json(result.rows);
  } catch (err) {
    console.error("getExams error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function getExamById(req, res) {
  const { examId } = req.params;
  try {
    const examResult = await pool.query(
      `SELECT * FROM exams WHERE id = $1 AND is_deleted = false`,
      [examId]
    );
    if (!examResult.rows[0]) return res.status(404).json({ error: "Exam not found" });

    const qResult = await pool.query(
      `SELECT id, question_number, question_text, options, correct_answer, explanation
       FROM questions WHERE exam_id = $1 AND is_deleted = false ORDER BY question_number ASC`,
      [examId]
    );
    res.json({ exam: examResult.rows[0], questions: qResult.rows });
  } catch (err) {
    console.error("getExamById error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function createExam(req, res) {
  const { title, description, duration_minutes, questions } = req.body;
  const normalizedTitle = title?.trim();
  const safeQuestions = Array.isArray(questions) ? questions : [];

  if (!normalizedTitle) {
    return res.status(400).json({ error: "Title is required" });
  }

  const accessCode = Math.random().toString(36).slice(2, 8).toUpperCase();
  let client;

  try {
    client = await pool.connect();
    await client.query("BEGIN");

    const examResult = await client.query(
      `INSERT INTO exams (title, description, duration_minutes, total_questions, access_code, created_by)
       VALUES ($1, $2, $3, $4, $5, $6)
       RETURNING id`,
      [normalizedTitle, description?.trim() || "", duration_minutes || 60, safeQuestions.length, accessCode, req.user.id]
    );
    const examId = examResult.rows[0].id;

    for (let i = 0; i < safeQuestions.length; i++) {
      const q = safeQuestions[i];
      await client.query(
        `INSERT INTO questions (exam_id, question_number, question_text, options, correct_answer, explanation)
         VALUES ($1, $2, $3, $4, $5, $6)`,
        [examId, i + 1, q.question_text, JSON.stringify(q.options), q.correct_answer, q.explanation || ""]
      );
    }

    await client.query("COMMIT");
    res.status(201).json({ examId, accessCode });
  } catch (err) {
    if (client) {
      try {
        await client.query("ROLLBACK");
      } catch (rollbackErr) {
        console.error("createExam rollback error:", rollbackErr);
      }
    }
    console.error("createExam error:", err);
    res.status(500).json({ error: "Internal server error" });
  } finally {
    if (client) client.release();
  }
}

export async function updateExam(req, res) {
  const { examId } = req.params;
  const { title, description, duration_minutes, status, questions } = req.body;
  const hasQuestions = Array.isArray(questions);
  let client;

  try {
    client = await pool.connect();
    await client.query("BEGIN");

    await client.query(
      `UPDATE exams SET title = COALESCE($1, title), description = COALESCE($2, description),
       duration_minutes = COALESCE($3, duration_minutes), status = COALESCE($4, status),
       total_questions = COALESCE($5, total_questions), updated_at = NOW()
       WHERE id = $6 AND is_deleted = false`,
      [title, description, duration_minutes, status, hasQuestions ? questions.length : null, examId]
    );

    if (hasQuestions) {
      // Delete existing questions then re-insert
      await client.query(`DELETE FROM questions WHERE exam_id = $1`, [examId]);
      for (let i = 0; i < questions.length; i++) {
        const q = questions[i];
        await client.query(
          `INSERT INTO questions (exam_id, question_number, question_text, options, correct_answer, explanation)
           VALUES ($1, $2, $3, $4, $5, $6)`,
          [examId, i + 1, q.question_text, JSON.stringify(q.options), q.correct_answer, q.explanation || ""]
        );
      }
    }

    await client.query("COMMIT");
    res.json({ success: true });
  } catch (err) {
    if (client) {
      try {
        await client.query("ROLLBACK");
      } catch (rollbackErr) {
        console.error("updateExam rollback error:", rollbackErr);
      }
    }
    console.error("updateExam error:", err);
    res.status(500).json({ error: "Internal server error" });
  } finally {
    if (client) client.release();
  }
}

export async function deleteExam(req, res) {
  const { examId } = req.params;
  try {
    await pool.query(`UPDATE exams SET is_deleted = true, status = 'deleted' WHERE id = $1`, [examId]);
    res.json({ success: true });
  } catch (err) {
    console.error("deleteExam error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

// ─── Submissions ─────────────────────────────────────────────────────────────

export async function getSubmissions(req, res) {
  const { examId } = req.query;
  try {
    const params = [];
    let whereClause = "";
    if (examId) {
      params.push(examId);
      whereClause = `AND es.exam_id = $${params.length}`;
    }
    const result = await pool.query(
      `SELECT es.id, es.exam_id, es.user_id, es.score, es.total_correct, es.total_questions,
              es.time_spent, es.status, es.submitted_at,
              u.username, u.first_name, u.last_name,
              e.title AS exam_title
       FROM exam_submissions es
       JOIN users u ON u.id = es.user_id
       JOIN exams e ON e.id = es.exam_id
       WHERE es.status = 'submitted' ${whereClause}
       ORDER BY es.submitted_at DESC`,
      params
    );
    res.json(result.rows);
  } catch (err) {
    console.error("getSubmissions error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function getSubmissionDetail(req, res) {
  const { submissionId } = req.params;
  try {
    const subResult = await pool.query(
      `SELECT es.*, u.username, u.first_name, u.last_name, e.title AS exam_title
       FROM exam_submissions es
       JOIN users u ON u.id = es.user_id
       JOIN exams e ON e.id = es.exam_id
       WHERE es.id = $1`,
      [submissionId]
    );
    if (!subResult.rows[0]) return res.status(404).json({ error: "Submission not found" });

    const answersResult = await pool.query(
      `SELECT a.question_id, a.user_answer, a.is_correct,
              q.question_number, q.question_text, q.options, q.correct_answer, q.explanation
       FROM answers a
       JOIN questions q ON q.id = a.question_id
       WHERE a.submission_id = $1
       ORDER BY q.question_number ASC`,
      [submissionId]
    );

    res.json({ submission: subResult.rows[0], answers: answersResult.rows });
  } catch (err) {
    console.error("getSubmissionDetail error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

// ─── Dashboard stats ─────────────────────────────────────────────────────────

export async function getDashboardStats(req, res) {
  try {
    const [usersRes, examsRes, submissionsRes, avgScoreRes] = await Promise.all([
      pool.query(`SELECT COUNT(*) FROM users WHERE is_deleted = false AND role = 'student'`),
      pool.query(`SELECT COUNT(*) FROM exams WHERE is_deleted = false`),
      pool.query(`SELECT COUNT(*) FROM exam_submissions WHERE status = 'submitted'`),
      pool.query(`SELECT ROUND(AVG(score)::numeric, 1) AS avg_score FROM exam_submissions WHERE status = 'submitted'`),
    ]);
    res.json({
      totalStudents: parseInt(usersRes.rows[0].count),
      totalExams: parseInt(examsRes.rows[0].count),
      totalSubmissions: parseInt(submissionsRes.rows[0].count),
      avgScore: parseFloat(avgScoreRes.rows[0].avg_score) || 0,
    });
  } catch (err) {
    console.error("getDashboardStats error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

// ─── Classrooms ──────────────────────────────────────────────────────────────

export async function getClassrooms(req, res) {
  try {
    const result = await pool.query(
      `SELECT c.id, c.name, c.description, c.created_at,
              COUNT(cm.user_id) as student_count
       FROM classrooms c
       LEFT JOIN classroom_members cm ON c.id = cm.classroom_id
       WHERE c.is_deleted = false
       GROUP BY c.id
       ORDER BY c.created_at DESC`
    );
    res.json(result.rows);
  } catch (err) {
    console.error("getClassrooms error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function getClassroomById(req, res) {
  const { id } = req.params;
  try {
    const classroomResult = await pool.query(
      `SELECT * FROM classrooms WHERE id = $1 AND is_deleted = false`,
      [id]
    );

    if (classroomResult.rows.length === 0) {
      return res.status(404).json({ error: "Classroom not found" });
    }

    const membersResult = await pool.query(
      `SELECT u.id, u.username, u.email, u.first_name, u.last_name, cm.added_at
       FROM classroom_members cm
       JOIN users u ON cm.user_id = u.id
       WHERE cm.classroom_id = $1 AND u.is_deleted = false
       ORDER BY cm.added_at DESC`,
      [id]
    );

    res.json({
      classroom: classroomResult.rows[0],
      members: membersResult.rows,
    });
  } catch (err) {
    console.error("getClassroomById error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function createClassroom(req, res) {
  const { name, description } = req.body;
  
  if (!name?.trim()) {
    return res.status(400).json({ error: "Classroom name is required" });
  }

  try {
    const result = await pool.query(
      `INSERT INTO classrooms (name, description, created_by)
       VALUES ($1, $2, $3)
       RETURNING *`,
      [name.trim(), description?.trim() || "", req.user?.id]
    );

    res.status(201).json(result.rows[0]);
  } catch (err) {
    console.error("createClassroom error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function updateClassroom(req, res) {
  const { id } = req.params;
  const { name, description } = req.body;

  if (!name?.trim()) {
    return res.status(400).json({ error: "Classroom name is required" });
  }

  try {
    const result = await pool.query(
      `UPDATE classrooms
       SET name = $1, description = $2, updated_at = NOW()
       WHERE id = $3 AND is_deleted = false
       RETURNING *`,
      [name.trim(), description?.trim() || "", id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: "Classroom not found" });
    }

    res.json(result.rows[0]);
  } catch (err) {
    console.error("updateClassroom error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function deleteClassroom(req, res) {
  const { id } = req.params;

  try {
    const result = await pool.query(
      `UPDATE classrooms SET is_deleted = true WHERE id = $1 RETURNING id`,
      [id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: "Classroom not found" });
    }

    res.json({ message: "Classroom deleted successfully" });
  } catch (err) {
    console.error("deleteClassroom error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function addStudentToClassroom(req, res) {
  const { classroomId } = req.params;
  const { userId } = req.body;

  if (!userId) {
    return res.status(400).json({ error: "User ID is required" });
  }

  try {
    // Check if classroom exists
    const classroomCheck = await pool.query(
      `SELECT id FROM classrooms WHERE id = $1 AND is_deleted = false`,
      [classroomId]
    );

    if (classroomCheck.rows.length === 0) {
      return res.status(404).json({ error: "Classroom not found" });
    }

    // Check if user exists and is a student
    const userCheck = await pool.query(
      `SELECT id, role FROM users WHERE id = $1 AND is_deleted = false`,
      [userId]
    );

    if (userCheck.rows.length === 0) {
      return res.status(404).json({ error: "User not found" });
    }

    if (userCheck.rows[0].role !== 'student') {
      return res.status(400).json({ error: "Only students can be added to classrooms" });
    }

    // Add student to classroom (or ignore if already exists)
    const result = await pool.query(
      `INSERT INTO classroom_members (classroom_id, user_id)
       VALUES ($1, $2)
       ON CONFLICT (classroom_id, user_id) DO NOTHING
       RETURNING *`,
      [classroomId, userId]
    );

    if (result.rows.length === 0) {
      return res.status(409).json({ error: "Student already in classroom" });
    }

    res.status(201).json({ message: "Student added to classroom successfully" });
  } catch (err) {
    console.error("addStudentToClassroom error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function removeStudentFromClassroom(req, res) {
  const { classroomId, userId } = req.params;

  try {
    const result = await pool.query(
      `DELETE FROM classroom_members
       WHERE classroom_id = $1 AND user_id = $2
       RETURNING *`,
      [classroomId, userId]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: "Student not found in classroom" });
    }

    res.json({ message: "Student removed from classroom successfully" });
  } catch (err) {
    console.error("removeStudentFromClassroom error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

// ─── Exam Logs ───────────────────────────────────────────────────────────────

export async function getExamLogs(req, res) {
  const { examId, userId, eventType, startDate, endDate, limit = 100 } = req.query;

  try {
    let query = `
      SELECT 
        l.id,
        l.event_type,
        l.event_data,
        l.created_at,
        u.username,
        u.first_name,
        u.last_name,
        e.title as exam_title,
        e.access_code as exam_code
      FROM exam_logs l
      LEFT JOIN users u ON l.user_id = u.id
      LEFT JOIN exams e ON l.exam_id = e.id
      WHERE 1=1
    `;
    const params = [];
    let paramIndex = 1;

    if (examId) {
      query += ` AND l.exam_id = $${paramIndex}`;
      params.push(examId);
      paramIndex++;
    }

    if (userId) {
      query += ` AND l.user_id = $${paramIndex}`;
      params.push(userId);
      paramIndex++;
    }

    if (eventType) {
      query += ` AND l.event_type = $${paramIndex}`;
      params.push(eventType);
      paramIndex++;
    }

    if (startDate) {
      query += ` AND l.created_at >= $${paramIndex}`;
      params.push(startDate);
      paramIndex++;
    }

    if (endDate) {
      query += ` AND l.created_at <= $${paramIndex}`;
      params.push(endDate);
      paramIndex++;
    }

    query += ` ORDER BY l.created_at DESC LIMIT $${paramIndex}`;
    params.push(parseInt(limit));

    const result = await pool.query(query, params);
    res.json(result.rows);
  } catch (err) {
    console.error("getExamLogs error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function getExamLogStats(req, res) {
  const { examId, userId } = req.query;

  try {
    let query = `
      SELECT 
        event_type,
        COUNT(*) as count
      FROM exam_logs
      WHERE 1=1
    `;
    const params = [];
    let paramIndex = 1;

    if (examId) {
      query += ` AND exam_id = $${paramIndex}`;
      params.push(examId);
      paramIndex++;
    }

    if (userId) {
      query += ` AND user_id = $${paramIndex}`;
      params.push(userId);
      paramIndex++;
    }

    query += ` GROUP BY event_type ORDER BY count DESC`;

    const result = await pool.query(query, params);
    res.json(result.rows);
  } catch (err) {
    console.error("getExamLogStats error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

// ─── Recycle Bin Endpoints ───────────────────────────────────────────────

export async function getRecycleBin(req, res) {
  try {
    const [users, exams, questions, classrooms] = await Promise.all([
      pool.query(`SELECT id, username, email, first_name, last_name, role, created_at FROM users WHERE is_deleted = true ORDER BY created_at DESC`),
      pool.query(`SELECT id, title, description, access_code, status, created_at FROM exams WHERE is_deleted = true ORDER BY created_at DESC`),
      pool.query(`SELECT id, exam_id, question_number, question_text, created_at FROM questions WHERE is_deleted = true ORDER BY created_at DESC`),
      pool.query(`SELECT id, name, description, created_at FROM classrooms WHERE is_deleted = true ORDER BY created_at DESC`),
    ]);
    res.json({
      users: users.rows,
      exams: exams.rows,
      questions: questions.rows,
      classrooms: classrooms.rows,
    });
  } catch (err) {
    console.error("getRecycleBin error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function restoreUser(req, res) {
  const { userId } = req.params;
  try {
    await pool.query(`UPDATE users SET is_deleted = false WHERE id = $1`, [userId]);
    res.json({ success: true });
  } catch (err) {
    console.error("restoreUser error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function restoreExam(req, res) {
  const { examId } = req.params;
  try {
    await pool.query(`UPDATE exams SET is_deleted = false, status = 'draft' WHERE id = $1`, [examId]);
    res.json({ success: true });
  } catch (err) {
    console.error("restoreExam error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function restoreQuestion(req, res) {
  const { questionId } = req.params;
  try {
    await pool.query(`UPDATE questions SET is_deleted = false WHERE id = $1`, [questionId]);
    res.json({ success: true });
  } catch (err) {
    console.error("restoreQuestion error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function restoreClassroom(req, res) {
  const { classroomId } = req.params;
  try {
    await pool.query(`UPDATE classrooms SET is_deleted = false WHERE id = $1`, [classroomId]);
    res.json({ success: true });
  } catch (err) {
    console.error("restoreClassroom error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function permanentlyDeleteUser(req, res) {
  const { userId } = req.params;
  try {
    await pool.query(`DELETE FROM users WHERE id = $1`, [userId]);
    res.json({ success: true });
  } catch (err) {
    console.error("permanentlyDeleteUser error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function permanentlyDeleteExam(req, res) {
  const { examId } = req.params;
  try {
    await pool.query(`DELETE FROM exams WHERE id = $1`, [examId]);
    res.json({ success: true });
  } catch (err) {
    console.error("permanentlyDeleteExam error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function permanentlyDeleteQuestion(req, res) {
  const { questionId } = req.params;
  try {
    await pool.query(`DELETE FROM questions WHERE id = $1`, [questionId]);
    res.json({ success: true });
  } catch (err) {
    console.error("permanentlyDeleteQuestion error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

// ─── Exam Sessions ──────────────────────────────────────────────────────────

export async function getExamSessions(req, res) {
  const { examId } = req.params;
  try {
    // Get all students who have ANY activity for this exam (logs OR submissions)
    const result = await pool.query(
      `SELECT 
        u.id as user_id, u.username, u.first_name, u.last_name,
        es.id as submission_id, es.score, es.total_correct, es.total_questions,
        es.time_spent, es.status as submission_status, es.submitted_at,
        COALESCE(es.created_at, MIN(l.created_at)) as started_at,
        COUNT(CASE WHEN l.event_type IN ('fullscreen_exit','window_blur','tab_hidden','monitoring_violation') THEN 1 END) as suspicious_count,
        COUNT(CASE WHEN l.event_type = 'camera_snapshot' THEN 1 END) as snapshot_count,
        COUNT(CASE WHEN l.event_type = 'monitoring_message' THEN 1 END) as message_count,
        COUNT(CASE WHEN l.event_type = 'monitoring_disqualify' THEN 1 END) as disqualified,
        COUNT(l.id) as total_events,
        CASE 
          WHEN COUNT(CASE WHEN l.event_type = 'monitoring_disqualify' THEN 1 END) > 0 THEN 'disqualified'
          WHEN es.status = 'submitted' THEN 'submitted'
          WHEN es.status = 'in_progress' THEN 'in_progress'
          ELSE 'joined'
        END as session_status
       FROM exam_logs l
       JOIN users u ON u.id = l.user_id
       LEFT JOIN exam_submissions es ON es.exam_id = $1 AND es.user_id = u.id
       WHERE l.exam_id = $1
       GROUP BY u.id, u.username, u.first_name, u.last_name,
                es.id, es.score, es.total_correct, es.total_questions,
                es.time_spent, es.status, es.submitted_at, es.created_at
       ORDER BY COALESCE(es.created_at, MIN(l.created_at)) DESC`,
      [examId]
    );
    res.json(result.rows);
  } catch (err) {
    console.error("getExamSessions error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function getStudentSessionDetail(req, res) {
  const { examId, studentId } = req.params;
  try {
    // Get submission info
    const submissionResult = await pool.query(
      `SELECT es.*, u.username, u.first_name, u.last_name, e.title as exam_title, e.duration_minutes
       FROM exam_submissions es
       JOIN users u ON u.id = es.user_id
       JOIN exams e ON e.id = es.exam_id
       WHERE es.exam_id = $1 AND es.user_id = $2`,
      [examId, studentId]
    );

    // Get all logs for this student+exam (excluding camera_snapshot images for the list — we return those separately)
    const logsResult = await pool.query(
      `SELECT id, event_type, 
        CASE WHEN event_type = 'camera_snapshot' 
          THEN jsonb_build_object('cameraType', event_data->>'cameraType', 'timestamp', event_data->>'timestamp')
          ELSE event_data 
        END as event_data,
        created_at
       FROM exam_logs
       WHERE exam_id = $1 AND user_id = $2
       ORDER BY created_at ASC`,
      [examId, studentId]
    );

    // Get camera snapshots separately (with images)
    const snapshotsResult = await pool.query(
      `SELECT id, event_data, created_at
       FROM exam_logs
       WHERE exam_id = $1 AND user_id = $2 AND event_type = 'camera_snapshot'
       ORDER BY created_at ASC`,
      [examId, studentId]
    );

    res.json({
      submission: submissionResult.rows[0] || null,
      timeline: logsResult.rows,
      snapshots: snapshotsResult.rows,
    });
  } catch (err) {
    console.error("getStudentSessionDetail error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

// ─── Monitoring Events ──────────────────────────────────────────────────────

export async function getMonitoringEvents(req, res) {
  const { examId } = req.params;
  try {
    const result = await pool.query(
      `SELECT 
        l.id, l.event_type, l.event_data, l.created_at,
        l.user_id as student_id,
        u.username, u.first_name, u.last_name
       FROM exam_logs l
       LEFT JOIN users u ON l.user_id = u.id
       WHERE l.exam_id = $1
         AND l.event_type IN (
           'monitoring_message', 'monitoring_disqualify',
           'monitoring_camera_check', 'monitoring_violation',
           'monitoring_student_joined', 'monitoring_student_left'
         )
       ORDER BY l.created_at DESC
       LIMIT 200`,
      [examId]
    );
    res.json(result.rows);
  } catch (err) {
    console.error("getMonitoringEvents error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}

export async function permanentlyDeleteClassroom(req, res) {
  const { classroomId } = req.params;
  try {
    await pool.query(`DELETE FROM classrooms WHERE id = $1`, [classroomId]);
    res.json({ success: true });
  } catch (err) {
    console.error("permanentlyDeleteClassroom error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
}
